services:
  - type: web
    name: izumi-bot
    repo: https://github.com/Akshay-Eypz/izumi-bot.git
    branch: main
    env: docker
    dockerfilePath: ../lib/Dockerfile
    plan: free
    autoDeploy: false
    envVars:
      - key: RENDER_NAME
        sync: false
        required: true
      - key: RENDER_API
        sync: false
        required: true
      - key: SESSION_ID
        sync: false
        required: true
      - key: PREFIX
        sync: false
      - key: SUDO
        sync: false
      - key: MODE
        value: "private"
      - key: PORT
        value: "3000"
